"""letter_generator.py
---------------------
Builds a PDF letter to the authority for a hazard incident, using reportlab.
Consumes the NORMALIZED incident fields (hazard_category / hazard_type / ...)
so the same letter works for road damage, waterlogging, and future hazards.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage)
from reportlab.lib.styles import getSampleStyleSheet

import hazard_types

LETTERS_DIR = os.path.join(os.path.dirname(__file__), "letters")
UPLOADS_DIR = os.path.join(os.path.dirname(__file__), "uploads")
os.makedirs(LETTERS_DIR, exist_ok=True)

AUTHORITY_NAME = os.environ.get("AUTHORITY_NAME", "Public Works Department")
AUTHORITY_ADDRESS = os.environ.get("AUTHORITY_ADDRESS", "[Authority address here]")
SENDER_NAME = os.environ.get("SENDER_NAME", "SmartSurround Monitoring System")
SENDER_CONTACT = os.environ.get("SENDER_CONTACT", "[Your contact email]")


def humanize_label(value):
    return hazard_types.humanize_label(value)


def _val(detection, key, default=None):
    try:
        v = detection[key]
        return default if v is None else v
    except (KeyError, IndexError):
        return default


def _resolve_image(detection):
    try:
        raw = (detection["image_path"] or "").strip()
    except (KeyError, IndexError):
        raw = ""
    if not raw:
        return None
    if os.path.isabs(raw) and os.path.exists(raw):
        return raw
    candidate = os.path.join(UPLOADS_DIR, os.path.basename(raw.replace("\\", "/")))
    return candidate if os.path.exists(candidate) else None


def generate_letter(detection) -> str:
    filename = f"letter_detection_{detection['id']}.pdf"
    filepath = os.path.join(LETTERS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4, pageCompression=0,
                            topMargin=2 * cm, bottomMargin=2 * cm,
                            leftMargin=2 * cm, rightMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    today = datetime.now().strftime("%d %B %Y")

    hazard_category = _val(detection, "hazard_category", "road_damage")
    hazard_label = humanize_label(hazard_category)
    hazard_type = _val(detection, "hazard_type",
                       _val(detection, "damage_class"))
    hazard_type_label = humanize_label(hazard_type)
    confidence = _val(detection, "confidence")
    location_name = _val(detection, "location_name")

    story.append(Paragraph(f"Date: {today}", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(f"To,<br/>{AUTHORITY_NAME}<br/>{AUTHORITY_ADDRESS}",
                           styles["Normal"]))
    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(
        f"<b>Subject: Report of {hazard_label} Requiring Attention</b>",
        styles["Heading3"]))
    story.append(Spacer(1, 0.4 * cm))

    lat = _val(detection, "lat", "N/A")
    lon = _val(detection, "lon", "N/A")
    source_label = ("an automated roadside monitoring post"
                    if _val(detection, "source") == "esp32"
                    else "a citizen complaint submitted through the SmartSurround portal")
    confidence_text = (f"{round(confidence * 100, 1)}%" if confidence is not None else "N/A")

    body = f"""
    Dear Sir/Madam,<br/><br/>
    This is an automated notice generated by the SmartSurround monitoring system,
    following manual verification by a system administrator.<br/><br/>
    A hazard classified as <b>{hazard_label}</b> (type: <b>{hazard_type_label}</b>,
    detection confidence: {confidence_text}) was identified via {source_label}
    at the following location:<br/><br/>
    <b>Location:</b> {location_name or "N/A"}<br/>
    <b>Latitude:</b> {lat} &nbsp;&nbsp; <b>Longitude:</b> {lon}<br/><br/>
    A verified snapshot of the affected location is attached below for reference.
    We request that the relevant maintenance team assess and address this condition
    at the earliest opportunity, particularly given the safety risk posed to the
    public.<br/><br/>
    """
    story.append(Paragraph(body, styles["Normal"]))

    if _val(detection, "description"):
        story.append(Paragraph(f"<b>Reporter's note:</b> {detection['description']}",
                               styles["Normal"]))
        story.append(Spacer(1, 0.4 * cm))

    img_path = _resolve_image(detection)
    if img_path:
        try:
            story.append(Spacer(1, 0.3 * cm))
            story.append(RLImage(img_path, width=10 * cm, height=7.5 * cm))
        except Exception:
            pass

    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(f"Regards,<br/>{SENDER_NAME}<br/>{SENDER_CONTACT}",
                           styles["Normal"]))

    doc.build(story)
    return filepath